name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Push Docker Image
        run: |
          gcloud builds submit --tag gcr.io/YOUR_PROJECT_ID/YOUR_IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy YOUR_SERVICE_NAME \
            --image gcr.io/YOUR_PROJECT_ID/YOUR_IMAGE_NAME \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
